services:
  mongodb:
    image: mongo:7.0
    container_name: sunx-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sunx_loyalty
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sunx-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sunx-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/sunx_loyalty?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - sunx-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: sunx-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - sunx-network

volumes:
  mongodb_data:

networks:
  sunx-network:
    driver: bridge
