version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: sunx-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure-mongo-password-change-this
      MONGO_INITDB_DATABASE: sunx_loyalty
    volumes:
      - mongodb_data:/data/db
    networks:
      - sunx-network
    ports:
      - "27017:27017"

  # Backend API (from Docker Hub)
  backend:
    image: sherluck007/sunx-loyalty-backend:latest
    container_name: sunx-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:secure-mongo-password-change-this@mongodb:27017/sunx_loyalty?authSource=admin
      - JWT_SECRET=sunx-super-secure-jwt-key-change-this-in-production
      - JWT_EXPIRE=7d
      - PORT=5000
      - ADMIN_EMAIL=admin@sunx.com
      - ADMIN_PASSWORD=admin123
      - CORS_ORIGIN=http://45.93.138.5,https://yourdomain.com
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - sunx-network
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (locally built with fixed API URL)
  frontend:
    image: sunx-loyalty-frontend-fixed:latest
    container_name: sunx-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - sunx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  sunx-network:
    driver: bridge
