version: '3.8'

services:
  frontend:
    image: sherluck007/sunx-loyalty-frontend:latest
    container_name: sunx-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl:/etc/ssl:ro
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - sunx-network
    restart: unless-stopped

  backend:
    image: sherluck007/sunx-loyalty-backend:latest
    container_name: sunx-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/sunx-loyalty
      - JWT_SECRET=sunx-loyalty-super-secret-jwt-key-2024-production
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - sunx-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: sunx-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sunx-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  sunx-network:
    driver: bridge
