name: installer_flutter
description: SunX Installer Android app using Flutter Material 3 and real backend API
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/

